### ISSUE TITLE
下载的文本文件无换行

### ISSUE THREAD

**Issue by rxnwin** [kenanpengyou/dir-tree-noter#1]
下载的文本文件无换行，复制出的结果却无问题。求解决。
另请求提高默认的目录读取层级，谢谢。

**Comment by kenanpengyou** [comment]
@rxnwin 重新试了下都是有换行的。
注意虽然下载的文件是`.txt`，但不能用记事本来看，随便用Sublime Text，Visual Studio Code一类的编辑器来查看即可。
