### ISSUE TITLE
可以支持忽略某个文件夹吗？

### ISSUE THREAD

**Issue by zhenzhenChange** [kenanpengyou/dir-tree-noter#2]
# 支持忽略配置吗

比如忽略 node_modules 文件夹

虽然删除该文件夹再生成也行。。。。

**Comment by kenanpengyou** [comment]
因为也支持多个文件夹，所以可以考虑排除node_modules，直接剩余的其他文件夹，一起丢到框里。

**Comment by zhenzhenChange** [comment]
是的，刚刚试了一下，确实OK。
